// src/app/beat/beat.component.ts
import {Component, Input} from '@angular/core';
import {Beat} from '../beat';
import {Note} from '../note.enum';

@Component({
  selector: 'app-beat',
  templateUrl: './beat.component.html',
  styleUrls: ['./beat.component.css']
})
export class BeatComponent {

  @Input() beat: Beat;

  constructor() {
  }

  onClick() {
    this.beat.note = (this.beat.note != Note.Rest ? Note.Rest : Note.Play);
  }

  onDoubleClick() {
    this.beat.note = Note.Accent;
  }

  buttonClass(): string {

    var base: string = 'btn btn-lg';
    switch (this.beat.note) {
      case Note.Rest: {
        return `${base} btn-outline-secondary`;
      }
      case Note.Play: {
        return `${base} btn-secondary`;
      }
      case Note.Accent: {
        return `${base} btn-success`;
      }
      default: {
        return `${base} btn-outline-warning`;
      }
    }
  }
}

<div class="flex-fill">
  <div class="btn-group" role="group" aria-label="">
    <button type="button" [ngClass]="buttonClass()" (click)="onClick()" (dblclick)="onDoubleClick()">{{ beat.index }}</button>
    <!--'btn btn-lg': true,-->
    <!--'btn-outline-secondary': beat.note == 0,-->
    <!--'btn-secondary': beat.note == 1,-->
    <!--'btn-success': beat.note == 2}"-->

  </div>
</div>

// src/components/Beat.tsx
import React from 'react';
import { Button } from 'react-bootstrap';
import styled from 'styled-components';

import type { Beat } from '../models/beat';
import { Note } from '../models/note.enum';

const StyledButton = styled(Button)`
    transition: none;
    width: 3em;
    height: 3em;
`;

type Props = {
    beat: Beat;
    isDisabled: boolean;
    onClick: (index: number) => void;
    onDoubleClick: (index: number) => void;
};

const getButtonVariant = (note: Note): string => {
    switch (note) {
        case Note.Rest: {
            return 'outline-secondary';
        }
        case Note.Play: {
            return 'secondary';
        }
        case Note.Accent: {
            return 'warning';
        }
        default: {
            return 'outline-error';
        }
    }
};

export const BeatComponent: React.FC<Props> = ({ beat, isDisabled, onClick, onDoubleClick }) => {
    return (
        <div className="flex-fill">
            <div aria-label="" className="btn-group" role="group">
                <StyledButton
                    disabled={isDisabled}
                    onClick={() => onClick(beat.index)}
                    onDoubleClick={() => onDoubleClick(beat.index)}
                    size="lg"
                    variant={getButtonVariant(beat.note)}
                >
                    {beat.index + 1}
                </StyledButton>
            </div>
        </div>
    );
};
