// src/components/TimeSignature.tsx
import type { ChangeEvent } from 'react';
import React from 'react';

import { TimeSignature } from '../models/time-signature';
import { NoteLengthChooser } from './NoteLengthChooser';

type Props = {
    time: TimeSignature;
    isDisabled?: boolean;
    onChange: (time: TimeSignature) => void;
};

export const TimeSignatureComponent: React.FC<Props> = ({ isDisabled = false, onChange, time }) => {
    const handleUpperChange = (event: ChangeEvent<HTMLInputElement>) => {
        const upper = parseInt(event.target.value);
        onChange(new TimeSignature(upper, time.lower));
    };

    const handleLowerChange = (value: number) => {
        onChange(new TimeSignature(time.upper, value));
    };

    return (
        <div className="form-inline">
            <label className="sr-only">Time</label>
            <div className="input-group mb-2 mr-sm-2">
                <div className="input-group-prepend">
                    <div className="input-group-text">
                        {time.upper}/{time.lower}
                    </div>
                </div>
                <input
                    className="form-control"
                    disabled={isDisabled}
                    max="17"
                    min="1"
                    onChange={handleUpperChange}
                    type="number"
                    value={time.upper}
                />
            </div>
            <NoteLengthChooser
                choices={[2, 4, 8]}
                duration={time.lower}
                isDisabled={isDisabled}
                onSelect={handleLowerChange}
            />
        </div>
    );
};

// src/app/time-signature/time-signature.component.ts

import { Component, OnInit, Input, Output, EventEmitter} from '@angular/core';
import { TimeSignature} from '../time-signature';

@Component({
  selector: 'app-time-signature',
  templateUrl: './time-signature.component.html',
  styleUrls: ['./time-signature.component.css']
})
export class TimeSignatureComponent implements OnInit {

  @Input() time: TimeSignature;
  @Input() disabled: boolean;

  @Output() changed = new EventEmitter<TimeSignature>();

  constructor() { }

  ngOnInit() {
  }

  valueChange(event) {
    console.log(event);
    this.changed.emit(this.time);
  }

  setLower(value: number) {
    this.time.lower = value;
    this.changed.emit(this.time);
  }

}

<div class="form-inline">
 <label class="sr-only" for="beats">Time</label>
  <div class="input-group mb-2 mr-sm-2">
    <div class="input-group-prepend">
      <div class="input-group-text">{{ time.upper }}/{{ time.lower }}</div>
    </div>
    <input type="number" class="form-control" id="beats" min="1" max="17" [disabled]="disabled" (ngModelChange)="valueChange($event)" [(ngModel)]="time.upper">
    <app-note-length-chooser (changed)="setLower($event)" [duration]="time.lower" [choices]="[2,4,8]"></app-note-length-chooser>
  </div>
</div>
